import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import ProgressProvider from "@/contexts/ProgressProvider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background font-sans antialiased")}>
        <ProgressProvider>
          {children}
          <Toaster position='top-right' richColors />
        </ProgressProvider>
      </body>
    </html>
  );
}
